version: '2'
services:


    app:

        build: 
            context: ./project
            dockerfile: Dockerfile
        image: flask_test_image:latest

        container_name: flask_test_app
        restart: always

        volumes:
            - ./project:/project
        working_dir: /project

        ports:
            - 5000:5000


